# Estadistica Aplicada

# Sesion 3- 10 agosto

#Sebastian Aguirre 1947870

Numpy (Numerical Python) ayuda a manejar números en python (vectores, matrices, decimales)

La estructura básica de numpy son los arreglos (arrays) 
Un arreglo es una colección de objetos del mismo tipo

Vamos a suponer que tenemos las ventas de botellas de agua de la cafeteria de la facu

Lunes 23, Martes 45, Miercoles 34, Jueves 28, Viernes 20

In [1]:
import numpy as np

In [2]:
ventas = [23, 45, 34, 28, 20]

In [3]:
type(ventas)

list

In [4]:
ventas= np.array(ventas)

In [5]:
type(ventas)

numpy.ndarray

In [6]:
#suma

np.sum(ventas)

150

In [7]:
#multiplicacion

np.prod(ventas)

19706400

In [8]:
#media/ promedio

np.mean(ventas)

30.0

In [9]:
#valor maximo

np.max(ventas)

45

In [10]:
#valor minimo

np.min(ventas)

20

In [11]:
#ordenar

np.sort(ventas)

array([20, 23, 28, 34, 45])

In [12]:
#varianza poblacional

np.var(ventas)

78.8

In [13]:
#desviacion estandar poblacional

np.std(ventas)

8.87693640846886

In [14]:
#varianza muestral

np.var(ventas,ddof=1)

98.5

In [15]:
#desviacion estandar muestral

np.std(ventas,ddof=1)

9.924716620639604

In [16]:
#vector

np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [17]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [18]:
np.arange(1,100,15)

array([ 1, 16, 31, 46, 61, 76, 91])

In [27]:
#Numeros aleatorios de una distribucion uniforme
#Fijamos la semilla
np.random.seed(12)
#Generan numeros aleatorios
np.random.randint(0,25,10)

array([11,  6, 17,  2,  3,  3, 12, 16, 22, 17])